networks:
  hackrva:

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - hackrva
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.live.rule=Host(`live.hackrva.org`)"
      - "traefik.http.routers.live.entrypoints=web"
      - "traefik.http.services.live.loadbalancer.server.url=http://10.200.200.42:81/"

  backup:
    build:
      context: ./backup
    restart: unless-stopped
    env_file:
      - ./db.env
    networks:
      - hackrva
    volumes:
      - ./persist/mysql:/var/lib/mysql
      - /mnt/NAS/HRVAbackups/wiki/:/backup/NAS/wiki
      - ./persist/images/:/var/www/html/images
    labels:
      - "traefik.enabled=false"


  memberserver:
    image: hackrva/memberserver:latest
    env_file:
      - ./memberserver.env
    restart: unless-stopped
    networks:
      - hackrva
    labels:
      - "traefik.http.routers.memberserver.rule=Host(`members.hackrva.org`)"
      - "traefik.http.routers.memberserver.entrypoints=web"
      - "traefik.http.services.memberserver.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

  database:
    image: mariadb:10.3
    env_file:
      - ./db.env
    restart: unless-stopped
    networks:
      - hackrva
    volumes:
      - ./persist/mysql:/var/lib/mysql

  wiki:
    image: mediawiki:stable
    env_file:
      - ./mediawiki.env
    restart: unless-stopped
    networks:
      - hackrva
    volumes:
      - ./wiki/uploads.ini/:/usr/local/etc/php/conf.d/uploads.ini
      - ./wiki/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./persist/images:/var/www/html/images
    labels:
      - "traefik.http.routers.wiki.rule=Host(`wiki.hackrva.org`)"
      - "traefik.http.routers.wiki.entrypoints=web"
      - "traefik.http.services.wiki.loadbalancer.server.port=80"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.10
    volumes:
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - '8883:8883'
      - '1883:1883'
    restart: unless-stopped
    networks:
      - hackrva
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "test", "-C", "1"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.enabled=false"
