version: '2'
networks:
  hackrva:
    driver: bridge
volumes:
  certstore:
services:
  backup:
    build:
      context: ./backup
    volumes:
      - ./persist/mysql:/var/lib/mysql
      - /mnt/NAS/HRVAbackups/wiki/:/backup/NAS/wiki
      - ./persist/images:/var/www/html/images
  gateway:
    build: ./gateway
    ports:
      - 80:80
      - 443:443
    networks:
      hackrva:
        aliases:
          - gateway
    volumes:
      - ./gateway/sites:/usr/local/apache2/conf/sites
      - certstore:/etc/letsencrypt
  memberserver:
    image: hackrva/memberserver:latest
    env_file:
      - ./memberserver.env
    networks:
      hackrva:
        aliases:
          - memberserver
  database:
    build:
      context: ./database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      hackrva:
        aliases:
          - database
    volumes:
      - ./persist/mysql:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
  games:
    build: ./games
    networks:
      hackrva:
        aliases:
          - games
    volumes:
      - ./games/img:/usr/local/apache2/htdocs/img
      - ./games/css:/usr/local/apache2/htdocs/css
  wiki:
    build: ./wiki
    depends_on:
      - database
    networks:
      hackrva:
        aliases:
          - wiki
    volumes:
      - ./persist/images:/var/www/html/images
  um3wooter:
    build: um3-wooter
    env_file:
      ./um3-wooter/.env
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.10
    volumes:
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - '8883:8883'
      - '1883:1883'
    restart: unless-stopped
    networks:
      hackrva:
        aliases:
          - mosquitto
#   chat:
#     build: ./chat
#     networks:
#       hackrva:
#         aliases:
#           - chat
