#!/bin/bash

set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/http.pid

if [ $(cat /etc/use_certbot) == "true" ]; then
  # Updating certbot certs needs to be done while apache is running
  echo "Using certbot for certs"
  /bin/update_certbot_certs.sh &
else
  # Using local certs for testing
  echo "Using local certs"
  /bin/update_local_certs.sh
fi

echo "Starting HTTP Server"

# Start Apache for real
exec httpd -DFOREGROUND

