#!/bin/bash

set -e

# Hit rate limit for games.hackrva.org

function update_certs() {

domains=( \
	"chat.hackrva.org" \
	"games.hackrva.org" \
	"hackrva.dynalias.org" \
	"wiki.hackrva.org" \
	)

# Don't run this too often or it will easily hit the rate limit
for domain in "${domains[@]}"
do

# Only run certbot newly if certs don't already exist
if [ ! -f /etc/letsencrypt/live/$domain/fullchain.pem ]; then

echo "Getting new cert"

certbot certonly \
  --agree-tos \
  --non-interactive \
  --webroot \
  -w "/usr/local/apache2/htdocs" \
  -d "$domain" \
  -m "hackrva@gmail.com"

fi

done

echo "Try renewing on Let's Encrypt"
/etc/periodic/daily/certbot-renew.sh

}

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/http.pid

update_certs & 

# Start Apache for real
exec httpd -DFOREGROUND

