# Keeping the database a separate container allows database backing up to be done in one place
FROM mariadb
# Needs to expose port 3306 to other docker containers for connecting to mysql
EXPOSE 3306

