networks:
  hackrva:

services:
  aptly:
    image: urpylka/aptly
    container_name: aptly
    ports:
      - 9998:8080
      - 9997:80
    env_file:
      - ../aptly.env
    volumes:
      - $BACKUP_DIR/aptly/data:/opt/aptly
      - $BACKUP_DIR/aptly/uploads:/opt/aptly/public/uploads
      - $BACKUP_DIR/aptly:/var/lib/aptly
      - $APTLY_GPG_DIR:/opt/aptly_gpg
    restart: unless-stopped
    networks:
      - hackrva
    labels:
      - "traefik.http.routers.aptly.rule=Host(`apt.hackrva.org`)"
      - "traefik.http.routers.aptly.entrypoints=web"
      - "traefik.http.services.aptly.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"

