networks:
  hackrva:

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - 9993:3001
    volumes:
      - $PERSIST_DIR/uptime-kuma:/app/data
    networks:
      - hackrva
    labels:
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.hackrva.org`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=web"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      - "com.centurylinklabs.watchtower.enable=true"

