networks:
  hackrva:

services:
  registry:
    image: registry:latest
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ../registry.password:/auth/registry.password
      - $PERSIST_DIR/registry_dir:/data
    ports:
      - 9988:5000
    networks:
      - hackrva
    labels:
      - "traefik.http.routers.registry.rule=Host(`registry.hackrva.org`)"
      - "traefik.http.routers.registry.entrypoints=web"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
      - "com.centurylinklabs.watchtower.enable=true"
